version: "3.3"
services:
  rabbit:
    image: rabbitmq:3.11.8-management
    ports:
     - "15672:15672"
  consumer1:
    build:
      context: .
      dockerfile: DockerfileConsumer1
    restart: always
    depends_on:
     - rabbit
  consumer2:
    build:
      context: .
      dockerfile: DockerfileConsumer1
    restart: always
    depends_on:
     - rabbit